Version info
softwareplanet/mec pull request #25
Opened 2022-04-05 13:49 UTC by MrIhor

2022-04-05 15:29 UTC, alexanderko requested changes

2022-04-05 15:29 UTC, alexanderko commented on gatsby-node.js
> +}
Встановити https://prettier.io/ з рекомендованих розширень та відформатувати код

2022-04-05 15:29 UTC, alexanderko commented on gatsby-node.js
> +    version: 'v1.0.0-beta1'
Читати з фалу з ферсією

2022-04-05 15:29 UTC, alexanderko commented on gatsby-node.js
> +  const myData = {
```suggestion
  const versionInfo = {
```

2022-04-05 15:29 UTC, alexanderko commented on gatsby-node.js
> +    id: createNodeId(`my-data-${myData.key}`),
Пожливо тут підійде унікальний id `'versionInfo'`

2022-04-05 15:29 UTC, alexanderko commented on gatsby-node.js
> +      type: 'versionInfo',
```suggestion
      type: 'String',
```

2022-04-05 15:29 UTC, alexanderko commented on gatsby-node.js
> +      mediaType: 'text/html',
```suggestion
      mediaType: 'text/plain',
```

2022-04-06 07:16 UTC, MrIhor commented on gatsby-node.js
> +      type: 'versionInfo',
type не відповідає за тип інформації, яку ми хочемо отримати. Це унікальне ім'я для директорії, яка буде відображатися в graphQl.('String' - не хоче приймати, білд ломається)

type {string}
An arbitrary globally unique type chosen by the plugin creating the node. Should be descriptive of the node as the type is used in forming GraphQL types so users will query for nodes based on the type chosen here. Nodes of a given type can only be created by one plugin.

2022-04-06 10:02 UTC, alexanderko commented on gatsby-node.js
> +      type NodeVersion implements Node @infer {
```suggestion
      type VersionInfo implements Node @infer {
```

2022-04-06 10:02 UTC, alexanderko commented on gatsby-node.js
> +    key: 'versionInfo',
Навіщо тут ця властивість

2022-04-06 12:54 UTC, merged